# Generated by Django 3.2.9 on 2021-11-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('vehicle_id', models.IntegerField()),
                ('weeks', models.IntegerField()),
                ('price', models.IntegerField()),
                ('payment_id', models.CharField(max_length=20)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
