# Generated by Django 3.2.9 on 2021-11-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_order_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carorder',
            name='weeks',
            field=models.IntegerField(default=1),
        ),
    ]
