# Generated by Django 3.2.9 on 2021-11-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='carorder',
            name='order_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
