# Generated by Django 3.2.9 on 2021-11-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_carorder_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carorder',
            name='order_id',
        ),
    ]
