# Generated by Django 3.2.9 on 2021-11-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_carorder_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carorder',
        ),
    ]
