# Generated by Django 3.2.9 on 2021-11-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
